server:
  port: 8001

spring:
  application:
    name: user-service
  datasource:
    url: jdbc:h2:file:./data/testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    constant:
      h2:
        console:
          enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka
